"""add_onboarding_field

Revision ID: d1018949caa0
Revises: ded3d7d7a140
Create Date: 2026-04-07 16:15:06.126075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1018949caa0'
down_revision: Union[str, None] = 'ded3d7d7a140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_completed_onboarding', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_completed_onboarding')
    # ### end Alembic commands ###
