"""initial schema

Revision ID: db49011b0da1
Revises: 
Create Date: 2026-04-01 19:45:20.762174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db49011b0da1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('folders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itineraries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('folder_id', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itinerary_days',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('itinerary_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_order', sa.Integer(), nullable=False),
    sa.Column('is_collapsed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itinerary_members',
    sa.Column('itinerary_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'editor', name='memberrole'), nullable=False),
    sa.Column('invited_via', sa.String(length=20), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('itinerary_id', 'user_id')
    )
    op.create_table('share_links',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('itinerary_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'editor', name='memberrole'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('itinerary_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('day_id', sa.String(), nullable=False),
    sa.Column('item_order', sa.Integer(), nullable=False),
    sa.Column('time_start', sa.String(length=5), nullable=True),
    sa.Column('time_end', sa.String(length=5), nullable=True),
    sa.Column('spot_name', sa.String(length=200), nullable=True),
    sa.Column('activity_desc', sa.Text(), nullable=True),
    sa.Column('transport', sa.String(length=50), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('booking_status', sa.String(length=20), nullable=True),
    sa.Column('booking_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('time_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spot_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activity_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transport_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cost_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booking_status_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booking_url_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rating_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['itinerary_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itinerary_items')
    op.drop_table('share_links')
    op.drop_table('itinerary_members')
    op.drop_table('itinerary_days')
    op.drop_table('itineraries')
    op.drop_table('folders')
    op.drop_table('users')
    # ### end Alembic commands ###
