"""widen_time_start_time_end_to_varchar50

Revision ID: ded3d7d7a140
Revises: d4b2e1f3a567
Create Date: 2026-04-02 20:31:41.478575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ded3d7d7a140'
down_revision: Union[str, None] = 'd4b2e1f3a567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('itinerary_items', 'time_start',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('itinerary_items', 'time_end',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('map_pins', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('version_history', 'entry_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('version_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('version_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('version_history', 'entry_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('map_pins', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('itinerary_items', 'time_end',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('itinerary_items', 'time_start',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    # ### end Alembic commands ###
